from django.db import models

# Create your models here.
COUNTRY_CHOICES = (
    ('INDIA', 'INDIA'),
    ('AFGHANISTAN', 'AFGHANISTAN'),
    ('ALBANIA', 'ALBANIA'),
    ('ALGERIA', 'ALGERIA'),
    ('ANDORRA', 'ANDORRA'),
    ('ANGOLA', 'ANGOLA'),
    ('ANTIGUA AND BARBUDA', 'ANTIGUA AND BARBUDA'),
    ('ARGENTINA', 'ARGENTINA'),
    ('ARMENIA', 'ARMENIA'),
    ('AUSTRALIA', 'AUSTRALIA'),
    ('AUSTRIA', 'AUSTRIA'),
    ('AZERBAIJAN', 'AZERBAIJAN'),
    ('BAHAMAS', 'BAHAMAS'),
    ('BAHRAIN', 'BAHRAIN'),
    ('BANGLADESH', 'BANGLADESH'),
    ('BARBADOS', 'BARBADOS'),
    ('BELARUS', 'BELARUS'),
    ('BELGIUM', 'BELGIUM'),
    ('BELIZE', 'BELIZE'),
    ('BENIN', 'BENIN'),
    ('BHUTAN', 'BHUTAN'),
    ('BOLIVIA', 'BOLIVIA'),
    ('BOSNIA AND HERZEGOVINA', 'BOSNIA AND HERZEGOVINA'),
    ('BOTSWANA', 'BOTSWANA'),
    ('BRAZIL', 'BRAZIL'),
    ('BRUNEI DARUSSALAM', 'BRUNEI DARUSSALAM'),
    ('BULGARIA', 'BULGARIA'),
    ('BURKINA FASO', 'BURKINA FASO'),
    ('BURUNDI', 'BURUNDI'),
    ('CABO VERDE', 'CABO VERDE'),
    ('CAMBODIA', 'CAMBODIA'),
    ('CAMEROON', 'CAMEROON'),
    ('CANADA', 'CANADA'),
    ('CENTRAL AFRICAN REPUBLIC', 'CENTRAL AFRICAN REPUBLIC'),
    ('CHAD', 'CHAD'),
    ('CHILE', 'CHILE'),
    ('CHINA', 'CHINA'),
    ('COLOMBIA', 'COLOMBIA'),
    ('COMOROS', 'COMOROS'),
    ('CONGO', 'CONGO'),
    ('CONGO, DEMOCRATIC REPUBLIC OF THE', 'CONGO, DEMOCRATIC REPUBLIC OF THE'),
    ('COSTA RICA', 'COSTA RICA'),
    ('CROATIA', 'CROATIA'),
    ('CUBA', 'CUBA'),
    ('CYPRUS', 'CYPRUS'),
    ('CZECH REPUBLIC', 'CZECH REPUBLIC'),
    ('DENMARK', 'DENMARK'),
    ('DJIBOUTI', 'DJIBOUTI'),
    ('DOMINICA', 'DOMINICA'),
    ('DOMINICAN REPUBLIC', 'DOMINICAN REPUBLIC'),
    ('EAST TIMOR', 'EAST TIMOR'),
    ('ECUADOR', 'ECUADOR'),
    ('EGYPT', 'EGYPT'),
    ('EL SALVADOR', 'EL SALVADOR'),
    ('EQUATORIAL GUINEA', 'EQUATORIAL GUINEA'),
    ('ERITREA', 'ERITREA'),
    ('ESTONIA', 'ESTONIA'),
    ('ESWATINI', 'ESWATINI'),
    ('ETHIOPIA', 'ETHIOPIA'),
    ('FIJI', 'FIJI'),
    ('FINLAND', 'FINLAND'),
    ('FRANCE', 'FRANCE'),
    ('GABON', 'GABON'),
    ('GAMBIA', 'GAMBIA'),
    ('GEORGIA', 'GEORGIA'),
    ('GERMANY', 'GERMANY'),
    ('GHANA', 'GHANA'),
    ('GREECE', 'GREECE'),
    ('GRENADA', 'GRENADA'),
    ('GUATEMALA', 'GUATEMALA'),
    ('GUINEA', 'GUINEA'),
    ('GUINEA-BISSAU', 'GUINEA-BISSAU'),
    ('GUYANA', 'GUYANA'),
    ('HAITI', 'HAITI'),
    ('HONDURAS', 'HONDURAS'),
    ('HUNGARY', 'HUNGARY'),
    ('ICELAND', 'ICELAND'),
    ('INDONESIA', 'INDONESIA'),
    ('IRAN', 'IRAN'),
    ('IRAQ', 'IRAQ'),
    ('IRELAND', 'IRELAND'),
    ('ISRAEL', 'ISRAEL'),
    ('ITALY', 'ITALY'),
    ('JAMAICA', 'JAMAICA'),
    ('JAPAN', 'JAPAN'),
    ('JORDAN', 'JORDAN'),
    ('KAZAKHSTAN', 'KAZAKHSTAN'),
    ('KENYA', 'KENYA'),
    ('KIRIBATI', 'KIRIBATI'),
    ('KOREA, NORTH', 'KOREA, NORTH'),
    ('KOREA, SOUTH', 'KOREA, SOUTH'),
    ('KOSOVO', 'KOSOVO'),
    ('KUWAIT', 'KUWAIT'),
    ('KYRGYZSTAN', 'KYRGYZSTAN'),
    ('LAOS', 'LAOS'),
    ('LATVIA', 'LATVIA'),
    ('LEBANON', 'LEBANON'),
    ('LESOTHO', 'LESOTHO'),
    ('LIBERIA', 'LIBERIA'),
    ('LIBYA', 'LIBYA'),
    ('LIECHTENSTEIN', 'LIECHTENSTEIN'),
    ('LITHUANIA', 'LITHUANIA'),
    ('LUXEMBOURG', 'LUXEMBOURG'),
    ('MADAGASCAR', 'MADAGASCAR'),
    ('MALAWI', 'MALAWI'),
    ('MALAYSIA', 'MALAYSIA'),
    ('MALDIVES', 'MALDIVES'),
    ('MALI', 'MALI'),
    ('MALTA', 'MALTA'),
    ('MAROCCO', 'MAROCCO'),
    ('MAURITANIA', 'MAURITANIA'),
    ('MAURITIUS', 'MAURITIUS'),
    ('MEXICO', 'MEXICO'),
    ('MICRONESIA', 'MICRONESIA'),
    ('MOLDOVA', 'MOLDOVA'),
    ('MONACO', 'MONACO'),
    ('MONGOLIA', 'MONGOLIA'),
    ('MONTENEGRO', 'MONTENEGRO'),
    ('MOZAMBIQUE', 'MOZAMBIQUE'),
    ('MYANMAR', 'MYANMAR'),
    ('NAMIBIA', 'NAMIBIA'),
    ('NAURU', 'NAURU'),
    ('NEPAL', 'NEPAL'),
    ('NETHERLANDS', 'NETHERLANDS'),
    ('NEW ZEALAND', 'NEW ZEALAND'),
    ('NICARAGUA', 'NICARAGUA'),
    ('NIGER', 'NIGER'),
    ('NIGERIA', 'NIGERIA'),
    ('NORWAY', 'NORWAY'),
    ('OMAN', 'OMAN'),
    ('PAKISTAN', 'PAKISTAN'),
    ('PALAU', 'PALAU'),
    ('PANAMA', 'PANAMA'),
    ('PAPUA NEW GUINEA', 'PAPUA NEW GUINEA'),
    ('PARAGUAY', 'PARAGUAY'),
    ('PERU', 'PERU'),
    ('PHILIPPINES', 'PHILIPPINES'),
    ('POLAND', 'POLAND'),
    ('PORTUGAL', 'PORTUGAL'),
    ('QATAR', 'QATAR'),
    ('ROMANIA', 'ROMANIA'),
    ('RUSSIA', 'RUSSIA'),
    ('RWANDA', 'RWANDA'),
    ('SAINT KITTS AND NEVIS', 'SAINT KITTS AND NEVIS'),
    ('SAINT LUCIA', 'SAINT LUCIA'),
    ('SAINT VINCENT AND THE GRENADINES', 'SAINT VINCENT AND THE GRENADINES'),
    ('SAMOA', 'SAMOA'),
    ('SAN MARINO', 'SAN MARINO'),
    ('SAO TOME AND PRINCIPE', 'SAO TOME AND PRINCIPE'),
    ('SAUDI ARABIA', 'SAUDI ARABIA'),
    ('SENEGAL', 'SENEGAL'),
    ('SERBIA', 'SERBIA'),
    ('SEYCHELLES', 'SEYCHELLES'),
    ('SIERRA LEONE', 'SIERRA LEONE'),
    ('SINGAPORE', 'SINGAPORE'),
    ('SLOVAKIA', 'SLOVAKIA'),
    ('SLOVENIA', 'SLOVENIA'),
    ('SOLOMON ISLANDS', 'SOLOMON ISLANDS'),
    ('SOMALIA', 'SOMALIA'),
    ('SOUTH AFRICA', 'SOUTH AFRICA'),
    ('SOUTH SUDAN', 'SOUTH SUDAN'),
    ('SPAIN', 'SPAIN'),
    ('SRI LANKA', 'SRI LANKA'),
    ('SUDAN', 'SUDAN'),
    ('SURINAME', 'SURINAME'),
    ('SWEDEN', 'SWEDEN'),
    ('SWITZERLAND', 'SWITZERLAND'),
    ('SYRIA', 'SYRIA'),
    ('TAIWAN', 'TAIWAN'),
    ('TAJIKISTAN', 'TAJIKISTAN'),
    ('TANZANIA', 'TANZANIA'),
    ('THAILAND', 'THAILAND'),
    ('TOGO', 'TOGO'),
    ('TONGA', 'TONGA'),
    ('TRINIDAD AND TOBAGO', 'TRINIDAD AND TOBAGO'),
    ('TUNISIA', 'TUNISIA'),
    ('TURKMENISTAN', 'TURKMENISTAN'),
    ('TUVALU', 'TUVALU'),
    ('UGANDA', 'UGANDA'),
    ('UKRAINE', 'UKRAINE'),
    ('UNITED ARAB EMIRATES', 'UNITED ARAB EMIRATES'),
    ('UNITED KINGDOM', 'UNITED KINGDOM'),
    ('UNITED STATES OF AMERICA', 'UNITED STATES OF AMERICA'),
    ('URUGUAY', 'URUGUAY'),
    ('UZBEKISTAN', 'UZBEKISTAN'),
    ('VANUATU', 'VANUATU'),
    ('VATICAN CITY', 'VATICAN CITY'),
    ('VENEZUELA', 'VENEZUELA'),
    ('VIETNAM', 'VIETNAM'),
    ('YEMEN', 'YEMEN'),
    ('ZAMBIA', 'ZAMBIA'),
    ('ZIMBABWE', 'ZIMBABWE'),
)

CURRENCY_CHOICES = (
    ('AFN', 'Afghan Afghani'),
    ('ALL', 'Albanian Lek'),
    ('DZD', 'Algerian Dinar'),
    ('EUR', 'Euro'),
    ('AOA', 'Angolan Kwanza'),
    ('XCD', 'East Caribbean Dollar'),
    ('ARS', 'Argentine Peso'),
    ('AMD', 'Armenian Dram'),
    ('AUD', 'Australian Dollar'),
    ('AZN', 'Azerbaijani Manat'),
    ('BSD', 'Bahamian Dollar'),
    ('BHD', 'Bahraini Dinar'),
    ('BDT', 'Bangladeshi Taka'),
    ('BBD', 'Barbadian Dollar'),
    ('BYN', 'Belarusian Ruble'),
    ('BZD', 'Belize Dollar'),
    ('XOF', 'West African CFA Franc'),
    ('BTN', 'Bhutanese Ngultrum'),
    ('BOB', 'Bolivian Boliviano'),
    ('BAM', 'Bosnia and Herzegovina Convertible Mark'),
    ('BWP', 'Botswana Pula'),
    ('BRL', 'Brazilian Real'),
    ('BND', 'Brunei Dollar'),
    ('BGN', 'Bulgarian Lev'),
    ('BIF', 'Burundian Franc'),
    ('CVE', 'Cape Verdean Escudo'),
    ('KHR', 'Cambodian Riel'),
    ('XAF', 'Central African CFA Franc'),
    ('CLP', 'Chilean Peso'),
    ('CNY', 'Chinese Yuan'),
    ('COP', 'Colombian Peso'),
    ('KMF', 'Comorian Franc'),
    ('CDF', 'Congolese Franc'),
    ('CRC', 'Costa Rican Colón'),
    ('HRK', 'Croatian Kuna'),
    ('CUP', 'Cuban Peso'),
    ('CYP', 'Cypriot Pound'),
    ('CZK', 'Czech Koruna'),
    ('DKK', 'Danish Krone'),
    ('DJF', 'Djiboutian Franc'),
    ('XCD', 'Dominican Dollar'),
    ('DOP', 'Dominican Peso'),
    ('ETB', 'Ethiopian Birr'),
    ('FJD', 'Fijian Dollar'),
    ('FIM', 'Finnish Markka'),
    ('FRF', 'French Franc'),
    ('GMD', 'Gambian Dalasi'),
    ('GEK', 'Georgian Kupon Larit'),
    ('DEG', 'German Mark'),
    ('GHS', 'Ghanaian Cedi'),
    ('GRD', 'Greek Drachma'),
    ('XCD', 'Grenadian Dollar'),
    ('GTQ', 'Guatemalan Quetzal'),
    ('GNF', 'Guinean Franc'),
    ('GNB', 'Guinean Bissau Peso'),
    ('GYD', 'Guyanese Dollar'),
    ('HTG', 'Haitian Gourde'),
    ('HNL', 'Honduran Lempira'),
    ('HUF', 'Hungarian Forint'),
    ('ISK', 'Icelandic Króna'),
    ('IDR', 'Indonesian Rupiah'),
    ('IRR', 'Iranian Rial'),
    ('IQD', 'Iraqi Dinar'),
    ('IEP', 'Irish Pound'),
    ('ILS', 'Israeli New Shekel'),
    ('ITL', 'Italian Lira'),
    ('JMD', 'Jamaican Dollar'),
    ('JPY', 'Japanese Yen'),
    ('JOD', 'Jordanian Dinar'),
    ('KZT', 'Kazakhstani Tenge'),
    ('KES', 'Kenyan Shilling'),
    ('KID', 'Kiribati Dollar'),
    ('KPW', 'North Korean Won'),
    ('KRW', 'South Korean Won'),
    ('XK', 'Kosovar Euro'),
    ('KWD', 'Kuwaiti Dinar'),
    ('KGS', 'Kyrgyzstani Som'),
    ('LAK', 'Laotian Kip'),
    ('LVL', 'Latvian Lats'),
    ('LBP', 'Lebanese Pound'),
    ('LSL', 'Lesotho Loti'),
    ('LRD', 'Liberian Dollar'),
    ('LYD', 'Libyan Dinar'),
    ('CHF', 'Swiss Franc'),
    ('LTL', 'Lithuanian Litas'),
    ('LUF', 'Luxembourgian Franc'),
    ('MGA', 'Malagasy Ariary'),
    ('MWK', 'Malawian Kwacha'),
    ('MYR', 'Malaysian Ringgit'),
    ('MVR', 'Maldivian Rufiyaa'),
    ('XOF', 'West African CFA Franc'),
    ('MTL', 'Maltese Lira'),
    ('MAD', 'Moroccan Dirham'),
    ('MRU', 'Mauritanian Ouguiya'),
    ('MUR', 'Mauritian Rupee'),
    ('MXN', 'Mexican Peso'),
    ('FSM', 'Micronesian Dollar'),
    ('MDL', 'Moldovan Leu'),
    ('MCO', 'Monégasque Franc'),
    ('MNT', 'Mongolian Tugrik'),
    ('EUR', 'Montenegrin Euro'),
    ('MZN', 'Mozambican Metical'),
    ('MMK', 'Myanmar Kyat'),
    ('NAD', 'Namibian Dollar'),
    ('AUD', 'Nauruan Dollar'),
    ('NPR', 'Nepalese Rupee'),
    ('EUR', 'Dutch Euro'),
    ('NZD', 'New Zealand Dollar'),
    ('NIO', 'Nicaraguan Córdoba'),
    ('XOF', 'West African CFA Franc'),
    ('NGN', 'Nigerian Naira'),
    ('NOK', 'Norwegian Krone'),
    ('OMR', 'Omani Rial'),
    ('PKR', 'Pakistani Rupee'),
    ('USD', 'Palauan Dollar'),
    ('PAB', 'Panamanian Balboa'),
    ('PGK', 'Papua New Guinean Kina'),
    ('PYG', 'Paraguayan Guarani'),
    ('PEN', 'Peruvian Nuevo Sol'),
    ('PHP', 'Philippine Peso'),
    ('PLN', 'Polish Zloty'),
    ('EUR', 'Portuguese Euro'),
    ('QAR', 'Qatari Rial'),
    ('RON', 'Romanian Leu'),
    ('RUB', 'Russian Ruble'),
    ('RWF', 'Rwandan Franc'),
    ('XCD', 'Saint Kitts and Nevis Dollar'),
    ('XCD', 'Saint Lucian Dollar'),
    ('XCD', 'Saint Vincent and the Grenadines Dollar'),
    ('WST', 'Samoan Tala'),
    ('EUR', 'San Marinese Euro'),
    ('STN', 'São Tomé and Príncipe Dobra'),
    ('SAR', 'Saudi Riyal'),
    ('XOF', 'Senegalese Franc'),
    ('RSD', 'Serbian Dinar'),
    ('SCR', 'Seychellois Rupee'),
    ('SLL', 'Sierra Leonean Leone'),
    ('SGD', 'Singapore Dollar'),
    ('SKK', 'Slovak Koruna'),
    ('EUR', 'Slovenian Euro'),
    ('SBD', 'Solomon Islands Dollar'),
    ('SOS', 'Somali Shilling'),
    ('ZAR', 'South African Rand'),
    ('SSP', 'South Sudanese Pound'),
    ('EUR', 'Spanish Euro'),
    ('LKR', 'Sri Lankan Rupee'),
    ('SDG', 'Sudanese Pound'),
    ('SRD', 'Surinamese Dollar'),
    ('SEK', 'Swedish Krona'),
    ('CHF', 'Swiss Franc'),
    ('SYP', 'Syrian Pound'),
    ('TWD', 'New Taiwan Dollar'),
    ('TJS', 'Tajikistani Somoni'),
    ('TZS', 'Tanzanian Shilling'),
    ('THB', 'Thai Baht'),
    ('XOF', 'Togolese Franc'),
    ('TOP', 'Tongan Paʻanga'),
    ('TTD', 'Trinidad and Tobago Dollar'),
    ('TND', 'Tunisian Dinar'),
    ('TMT', 'Turkmenistani Manat'),
    ('AUD', 'Tuvaluan Dollar'),
    ('UGX', 'Ugandan Shilling'),
    ('UAH', 'Ukrainian Hryvnia'),
    ('AED', 'United Arab Emirates Dirham'),
    ('GBP', 'British Pound Sterling'),
    ('USD', 'United States Dollar'),
    ('UYU', 'Uruguayan Peso'),
    ('UZS', 'Uzbekistani Som'),
    ('VUV', 'Vanuatu Vatu'),
    ('EUR', 'Vatican City Euro'),
    ('VES', 'Venezuelan Bolívar Soberano'),
    ('VND', 'Vietnamese Dong'),
    ('YER', 'Yemeni Rial'),
    ('ZMW', 'Zambian Kwacha'),
    ('ZWL', 'Zimbabwean Dollar'),
)

LANGUAGE_CHOICES = (
    ('AFRIKAANS', 'AFRIKAANS'),
    ('ALBANIAN', 'ALBANIAN'),
    ('AMHARIC', 'AMHARIC'),
    ('ARABIC', 'ARABIC'),
    ('ARMENIAN', 'ARMENIAN'),
    ('ASSAMESE', 'ASSAMESE'),
    ('BASQUE', 'BASQUE'),
    ('BELARUSIAN', 'BELARUSIAN'),
    ('BENGALI', 'BENGALI'),
    ('BIHARI', 'BIHARI'),
    ('BOSNIAN', 'BOSNIAN'),
    ('BRETON', 'BRETON'),
    ('BULGARIAN', 'BULGARIAN'),
    ('BURMESE', 'BURMESE'),
    ('CATALAN', 'CATALAN'),
    ('CEBUANO', 'CEBUANO'),
    ('CHICHEWA', 'CHICHEWA'),
    ('CHINESE', 'CHINESE'),
    ('CORSICAN', 'CORSICAN'),
    ('CROATIAN', 'CROATIAN'),
    ('CZECH', 'CZECH'),
    ('DANISH', 'DANISH'),
    ('DUTCH', 'DUTCH'),
    ('ENGLISH', 'ENGLISH'),
    ('ESPERANTO', 'ESPERANTO'),
    ('ESTONIAN', 'ESTONIAN'),
    ('FILIPINO', 'FILIPINO'),
    ('FINNISH', 'FINNISH'),
    ('FRENCH', 'FRENCH'),
    ('FRISIAN', 'FRISIAN'),
    ('GALICIAN', 'GALICIAN'),
    ('GEORGIAN', 'GEORGIAN'),
    ('GERMAN', 'GERMAN'),
    ('GREEK', 'GREEK'),
    ('GUJARATI', 'GUJARATI'),
    ('HAITIAN CREOLE', 'HAITIAN CREOLE'),
    ('HAUSA', 'HAUSA'),
    ('HEBREW', 'HEBREW'),
    ('HINDI', 'HINDI'),
    ('HUNGARIAN', 'HUNGARIAN'),
    ('ICELANDIC', 'ICELANDIC'),
    ('IGBO', 'IGBO'),
    ('INDONESIAN', 'INDONESIAN'),
    ('IRISH', 'IRISH'),
    ('ITALIAN', 'ITALIAN'),
    ('JAPANESE', 'JAPANESE'),
    ('JAVANESE', 'JAVANESE'),
    ('KANNADA', 'KANNADA'),
    ('KAZAKH', 'KAZAKH'),
    ('KINYARWANDA', 'KINYARWANDA'),
    ('KOREAN', 'KOREAN'),
    ('KURDISH', 'KURDISH'),
    ('KYRGYZ', 'KYRGYZ'),
    ('LAO', 'LAO'),
    ('LATVIAN', 'LATVIAN'),
    ('LITHUANIAN', 'LITHUANIAN'),
    ('LUXEMBOURGISH', 'LUXEMBOURGISH'),
    ('Macedonian', 'MACEDONIAN'),
    ('MALAY', 'MALAY'),
    ('MALAYALAM', 'MALAYALAM'),
    ('MALTese', 'MALTese'),
    ('MAORI', 'MAORI'),
    ('MARATHI', 'MARATHI'),
    ('MONGOLIAN', 'MONGOLIAN'),
    ('MYANMAR (BURMESE)', 'MYANMAR (BURMESE)'),
    ('NEPALI', 'NEPALI'),
    ('NORWEGIAN', 'NORWEGIAN'),
    ('PASHTO', 'PASHTO'),
    ('PERSIAN', 'PERSIAN'),
    ('POLISH', 'POLISH'),
    ('PORTUGUESE', 'PORTUGUESE'),
    ('PUNJABI', 'PUNJABI'),
    ('ROMANIAN', 'ROMANIAN'),
    ('RUSSIAN', 'RUSSIAN'),
    ('Samoan', 'SAMOAN'),
    ('SANSKRIT', 'SANSKRIT'),
    ('SCOTS GAELIC', 'SCOTS GAELIC'),
    ('SERBO-CROATIAN', 'SERBO-CROATIAN'),
    ('SESOTHO', 'SESOTHO'),
    ('SHONA', 'SHONA'),
    ('SINDHI', 'SINDHI'),
    ('SINHALESE', 'SINHALESE'),
    ('SLOVAK', 'SLOVAK'),
    ('SLOVENIAN', 'SLOVENIAN'),
    ('SOMALI', 'SOMALI'),
    ('SPANISH', 'SPANISH'),
    ('SUNDANESE', 'SUNDANESE'),
    ('SWAHILI', 'SWAHILI'),
    ('SWEDISH', 'SWEDISH'),
    ('TAJIK', 'TAJIK'),
    ('TAMIL', 'TAMIL'),
    ('TATAR', 'TATAR'),
    ('TELUGU', 'TELUGU'),
    ('THAI', 'THAI'),
    ('TURKMEN', 'TURKMEN'),
    ('UIGHUR', 'UIGHUR'),
    ('UKRAINIAN', 'UKRAINIAN'),
    ('URDU', 'URDU'),
    ('UZBEK', 'UZBEK'),
    ('VIETNAMESE', 'VIETNAMESE'),
    ('WELSH', 'WELSH'),
    ('XHOSA', 'XHOSA'),
    ('YIDDISH', 'YIDDISH'),
    ('YORUBA', 'YORUBA'),
    ('ZULU', 'ZULU'),
)

ROLE_CHOICES = (
    ('User', 'User'),
    ('Admin', 'Admin'),
    ('SuperAdmin', 'SuperAdmin'),
    ('Moderator', 'Moderator'),
    ('Manager', 'Manager'),
    ('Employee', 'Employee'),
    ('Customer', 'Customer'),
    ('Supplier', 'Supplier'),
    ('Staff', 'Staff'),

)

DEPARTMENT_CHOICES = (
    ('IT', 'IT'),
    ('HR', 'HR'),
    ('Sales', 'Sales'),
    ('Marketing', 'Marketing'),
    ('Finance', 'Finance'),
    ('Operations', 'Operations'),
)

DESIGNATION_CHOICES = (
    ('CEO', 'CHIEF EXECUTIVE OFFICER'),
    ('CFO', 'CHIEF FINANCIAL OFFICER'),
    ('COO', 'CHIEF OPERATING OFFICER'),
    ('CTO', 'CHIEF TECHNOLOGY OFFICER'),
    ('CMO', 'CHIEF MARKETING OFFICER'),
    ('CIO', 'CHIEF INFORMATION OFFICER'),
    ('CHRO', 'CHIEF HUMAN RESOURCES OFFICER'),
    ('CSO', 'CHIEF STRATEGY OFFICER'),
    ('CDO', 'CHIEF DATA OFFICER'),
    ('CPO', 'CHIEF PRODUCT OFFICER'),
    ('CAO', 'CHIEF ADMINISTRATIVE OFFICER'),
    ('CLO', 'CHIEF LEGAL OFFICER'),
    ('CCO', 'CHIEF COMMERCIAL OFFICER'),
    ('VP', 'VICE PRESIDENT'),
    ('SVP', 'SENIOR VICE PRESIDENT'),
    ('EVP', 'EXECUTIVE VICE PRESIDENT'),
    ('DIRECTOR', 'DIRECTOR'),
    ('MANAGER', 'MANAGER'),
    ('ASSISTANT MANAGER', 'ASSISTANT MANAGER'),
    ('SUPERVISOR', 'SUPERVISOR'),
    ('TEAM LEAD', 'TEAM LEAD'),
    ('SENIOR ANALYST', 'SENIOR ANALYST'),
    ('ANALYST', 'ANALYST'),
    ('ASSOCIATE', 'ASSOCIATE'),
    ('COORDINATOR', 'COORDINATOR'),
    ('ADMINISTRATOR', 'ADMINISTRATOR'),
    ('OFFICER', 'OFFICER'),
    ('CLERK', 'CLERK'),
    ('ASSISTANT', 'ASSISTANT'),
    ('INTERNSHIP', 'INTERNSHIP'),
    ('EXECUTIVE', 'EXECUTIVE'),
    ('CONSULTANT', 'CONSULTANT'),
    ('ADVISOR', 'ADVISOR'),
    ('SPECIALIST', 'SPECIALIST'),
    ('ENGINEER', 'ENGINEER'),
    ('TECHNICIAN', 'TECHNICIAN'),
    ('ARCHITECT', 'ARCHITECT'),
    ('DEVELOPER', 'DEVELOPER'),
    ('DESIGNER', 'DESIGNER'),
    ('MARKETER', 'MARKETER'),
    ('SALES REP', 'SALES REPRESENTATIVE'),
    ('CUSTOMER SERVICE', 'CUSTOMER SERVICE'),
)

TIME_ZONE_CHOICES = (
    ('UTC-12:00', 'UTC-12:00 (Baker Island Time)'),
    ('UTC-11:00', 'UTC-11:00 (Niue Time, Samoa Time)'),
    ('UTC-10:00', 'UTC-10:00 (Hawaii-Aleutian Standard Time)'),
    ('UTC-09:00', 'UTC-09:00 (Alaska Standard Time)'),
    ('UTC-08:00', 'UTC-08:00 (Pacific Standard Time)'),
    ('UTC-07:00', 'UTC-07:00 (Mountain Standard Time)'),
    ('UTC-06:00', 'UTC-06:00 (Central Standard Time)'),
    ('UTC-05:00', 'UTC-05:00 (Eastern Standard Time)'),
    ('UTC-04:00', 'UTC-04:00 (Atlantic Standard Time)'),
    ('UTC-03:00', 'UTC-03:00 (Argentina Time, Brasilia Time)'),
    ('UTC-02:00', 'UTC-02:00 (South Georgia Time)'),
    ('UTC-01:00', 'UTC-01:00 (Azores Time, Cape Verde Time)'),
    ('UTC±00:00', 'UTC±00:00 (Greenwich Mean Time)'),
    ('UTC+01:00', 'UTC+01:00 (Central European Time)'),
    ('UTC+02:00', 'UTC+02:00 (Eastern European Time)'),
    ('UTC+03:00', 'UTC+03:00 (Moscow Time, East Africa Time)'),
    ('UTC+04:00', 'UTC+04:00 (Azerbaijan Time, Samara Time)'),
    ('UTC+05:00', 'UTC+05:00 (Pakistan Standard Time, Yekaterinburg Time)'),
    ('UTC+06:00', 'UTC+06:00 (Bangladesh Standard Time, Omsk Time)'),
    ('UTC+07:00', 'UTC+07:00 (Indochina Time, Krasnoyarsk Time)'),
    ('UTC+08:00', 'UTC+08:00 (China Standard Time, Singapore Time)'),
    ('UTC+09:00', 'UTC+09:00 (Japan Standard Time, Korea Standard Time)'),
    ('UTC+10:00', 'UTC+10:00 (Australian Eastern Standard Time, Vladivostok Time)'),
    ('UTC+11:00', 'UTC+11:00 (Solomon Islands Time, Magadan Time)'),
    ('UTC+12:00', 'UTC+12:00 (Fiji Time, Kamchatka Time)'),
)


ACCOUNT_STATUS_CHOICES = (
    ('Active', 'Active'),
    ('Inactive', 'Inactive'),
    ('Blocked', 'Blocked'),
)

class Users(AbstractUser):
    name = models.CharField(max_length=100, blank=True, null=True)
    email = models.EmailField(unique=True)
    phone = models.CharField(max_length=15, blank=True, null=True)
    address = models.TextField()
    city = models.CharField(max_length=50, blank=True, null=True)
    state = models.CharField(max_length=50, blank=True, null=True)
    pincode = models.CharField(max_length=10, blank=True, null=True)
    country = models.CharField(max_length=50, default="INDIA", choices=COUNTRY_CHOICES, blank=True, null=True)
    profile_pic = models.ImageField(upload_to='profile_pic/', blank=True, null=True)
    account_status = models.CharField(max_length=50, default="Active", choices=ACCOUNT_STATUS_CHOICES, blank=True, null=True)
    role = models.CharField(max_length=50, default="User", choices=ROLE_CHOICES, blank=True, null=True)
    dob = models.DateField(blank=True, null=True)
    username = models.CharField(max_length=50, unique=True)
    password = models.CharField(max_length=50)
    social_media_links = models.JSONField()(blank=True, null=True)
    additional_details = models.JSONField()(blank=True, null=True)
    language = models.CharField(max_length=50, default="English", choices=LANGUAGE_CHOICES, blank=True, null=True)
    department = models.CharField(max_length=50, blank=True, null=True, choices=DEPARTMENT_CHOICES)
    designation = models.CharField(max_length=50, blank=True, null=True, choices=DESIGNATION_CHOICES)
    time_zone = models.CharField(max_length=50, blank=True, null=True, choices=TIME_ZONE_CHOICES)
    last_login = models.DateTimeField(blank=True, null=True)
    last_device = models.CharField(max_length=100, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

